name: Test Sorare Login

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Esegui ogni giorno alle 9:00 UTC
    - cron: '0 9 * * *'
  workflow_dispatch:
    # Permette esecuzione manuale dal tab Actions

jobs:
  test-login:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Sorare Login
      env:
        SORARE_EMAIL: ${{ secrets.SORARE_EMAIL }}
        SORARE_PASSWORD: ${{ secrets.SORARE_PASSWORD }}
      run: |
        python test_login.py
    
    - name: Show result
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "✅ Login test PASSED"
        else
          echo "❌ Login test FAILED"
        fi
